
spring:
  datasource:
    name: restaurant  #数据库名
#    url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=GMT%2B8 #url
    url: jdbc:mysql://47.97.171.52:3307/restaurant?serverTimezone=GMT%2B8 #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com/example/restaurant_back/bean #配置实体类
server:
  port: 8081
  servlet:
    context-path: /




